restructure code to share generate across versions

diff --git a/generate/000_prereq b/generate/000_prereq
--- a/generate/000_prereq
+++ b/generate/000_prereq
@@ -7,7 +7,7 @@ if ! [ $# -eq 3 ]; then
 	exit 8
 fi
 
-verb="$1"
+sw="$1"
 verb="$2"
 script="$3"
 zospm=`whence zospm`
@@ -96,6 +96,7 @@ chmod u+x "${script}"
 
 cat << EOF >>${script}
 export PATH=${zospmdir}:\$PATH
+export sw="${sw}"
 . zospmsetswenv "${sw}"
 EOF
 
@@ -159,8 +160,8 @@ chkNode() {
 }
 
 chkzOSMF() {
-	if `undefinedProperty $ZWE1B0_HOSTNAME`; then
-		echo "000_prereq: need to specify ZWE1B0_HOSTNAME to configure Zowe" >&2
+	if `undefinedProperty $ZWE_HOSTNAME`; then
+		echo "000_prereq: need to specify ZWE_HOSTNAME to configure Zowe" >&2
 		return 4
 	fi
 	zosmfnetstat=`tsocmd netstat 2>/dev/null | grep IZUSVR | grep ".*Listen"`
@@ -171,9 +172,9 @@ chkzOSMF() {
 	fi
  	zosmfqualifiedport=`echo "${zosmfnetstat}" | awk '{ print $4 }'`
 	zosmfport=${zosmfqualifiedport##*.}
-	httpsget "https://${ZWE1B0_HOSTNAME}:${zosmfport}/zosmf/info" >/dev/null
+	httpsget "https://${ZWE_HOSTNAME}:${zosmfport}/zosmf/info" >/dev/null
 	if [ $rc -gt 0 ]; then
-		echo "000_prereq: unable to connect to https://${ZWE1B0_HOSTNAME}:${zosmfport}/zosmf/info. Start z/OSMF before configuring Zowe" >&2
+		echo "000_prereq: unable to connect to https://${ZWE_HOSTNAME}:${zosmfport}/zosmf/info. Start z/OSMF before configuring Zowe" >&2
 		return 4
 	fi
 	return 0
diff --git a/generate/002_zini b/generate/002_zini
--- a/generate/002_zini
+++ b/generate/002_zini
@@ -1,11 +1,12 @@
 #!/bin/sh
 
-if ! [ $# -eq 2 ]; then
-	echo "Syntax: 002_zini ENABLE|DISABLE <output-script>" >&2
+if ! [ $# -eq 3 ]; then
+	echo "Syntax: 002_zini <sw> CONFIG|DECONFIG <output-script>" >&2
 	exit 8
 fi
-verb="$1"
-script="$2"
+sw="$1"
+verb="$2"
+script="$3"
 
 zospm=`whence zospm`
 zospmdir=${zospm%/*}
@@ -16,42 +17,43 @@ cat << EOF >${script}
 #set -x
 export verb="${verb}"
 export PATH=${zospmdir}:\$PATH
-. zospmsetswenv zwe1b0
+export sw="${sw}"
+. zospmsetswenv "${sw}"
 
 set +x
 zowedir="\${ZOSPM_TGT_ZFSROOT}usr/lpp/zowe"
-zoweinstancedir="\${ZWE1B0_INSTANCE_ROOT}"
+zoweinstancedir="\${ZWE_INSTANCE_ROOT}"
 EOF
 
 if [ $? -gt 0 ]; then
-	echo "Unable to create ZWE1B0 Update script: ${script}." >&2
+	echo "Unable to create ${sw} Update script: ${script}." >&2
 	exit 16
 fi
 chmod u+x "${script}"
 
-if [ "${verb}" = "ENABLE" ]; then
+if [ "${verb}" = "CONFIG" ]; then
 cat <<'EOF' >>${script}
-	chkProperties "ZWE1B0_KEYSTORE_DIRECTORY ZWE1B0_LOGDIR ZWE1B0_INSTANCE_ROOT"
+	chkProperties "ZWE_KEYSTORE_DIRECTORY ZWE_LOGDIR ZWE_INSTANCE_ROOT"
 	if [ $? -gt 0 ]; then
 		echo "002_zini failed." >&2
 		exit 8
 	fi
 
-	rm -rf "${ZWE1B0_KEYSTORE_DIRECTORY}" "${ZWE1B0_LOGDIR}" "${ZWE1B0_INSTANCE_ROOT}"
-	mkdir -p "${ZWE1B0_KEYSTORE_DIRECTORY}" "${ZWE1B0_LOGDIR}" "${ZWE1B0_INSTANCE_ROOT}"
+	rm -rf "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}"
+	mkdir -p "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}"
 	rc=$?
 	if [ $rc -gt 0 ]; then
-		echo "Unable to create instance directories: ${ZWE1B0_KEYSTORE_DIRECTORY} ${ZWE1B0_LOGDIR} ${ZWE1B0_INSTANCE_ROOT}"
+		echo "Unable to create instance directories: ${ZWE_KEYSTORE_DIRECTORY} ${ZWE_LOGDIR} ${ZWE_INSTANCE_ROOT}"
 		exit $rd
 	fi
-	chmod -R 770 "${ZWE1B0_KEYSTORE_DIRECTORY}" "${ZWE1B0_LOGDIR}" "${ZWE1B0_INSTANCE_ROOT}" 
+	chmod -R 770 "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}" 
 	if [ $rc -gt 0 ]; then
-		echo "Unable to change ownership for instance directories: ${ZWE1B0_KEYSTORE_DIRECTORY} ${ZWE1B0_LOGDIR} ${ZWE1B0_INSTANCE_ROOT}"
+		echo "Unable to change ownership for instance directories: ${ZWE_KEYSTORE_DIRECTORY} ${ZWE_LOGDIR} ${ZWE_INSTANCE_ROOT}"
 		exit $rd
 	fi
-	chown ${ZWE1B0_ZOWEUSER}:${ZWE1B0_ADMINGRP} "${ZWE1B0_KEYSTORE_DIRECTORY}" "${ZWE1B0_LOGDIR}" "${ZWE1B0_INSTANCE_ROOT}" 
+	chown ${ZWE_ZOWEUSER}:${ZWE_ADMINGRP} "${ZWE_KEYSTORE_DIRECTORY}" "${ZWE_LOGDIR}" "${ZWE_INSTANCE_ROOT}" 
 	if [ $rc -gt 0 ]; then
-		echo "Unable to change ownership for instance directories: ${ZWE1B0_KEYSTORE_DIRECTORY} ${ZWE1B0_LOGDIR} ${ZWE1B0_INSTANCE_ROOT}"
+		echo "Unable to change ownership for instance directories: ${ZWE_KEYSTORE_DIRECTORY} ${ZWE_LOGDIR} ${ZWE_INSTANCE_ROOT}"
 		exit $rd
 	fi
 EOF
diff --git a/generate/003_cert b/generate/003_cert
--- a/generate/003_cert
+++ b/generate/003_cert
@@ -1,11 +1,12 @@
 #!/bin/sh
 
-if ! [ $# -eq 2 ]; then
-	echo "Syntax: 003_cert ENABLE|DISABLE <output-script>" >&2
+if ! [ $# -eq 3 ]; then
+	echo "Syntax: 003_cert <sw> CONFIG|DECONFIG <output-script>" >&2
 	exit 8
 fi
-verb="$1"
-script="$2"
+sw="$1"
+verb="$2"
+script="$3"
 
 zospm=`whence zospm`
 zospmdir=${zospm%/*}
@@ -16,18 +17,19 @@ cat << EOF >${script}
 #set -x
 export verb="${verb}"
 export PATH=${zospmdir}:\$PATH
-. zospmsetswenv zwe1b0
+export sw="${sw}"
+. zospmsetswenv "${sw}"
 
 set +x
 EOF
 
 if [ $? -gt 0 ]; then
-	echo "Unable to create ZWE1B0 Update script: ${script}." >&2
+	echo "Unable to create ${sw} Update script: ${script}." >&2
 	exit 16
 fi
 chmod u+x "${script}"
 
-if [ "${verb}" = "DISABLE" ]; then
+if [ "${verb}" = "DECONFIG" ]; then
 cat <<'EOF' >>${script}
 SetupCertificates() {
 	return 0
@@ -36,11 +38,11 @@ SetupRACF() {
 	return 0
 }
 SetupTopSecret() {
-	echo "003_cert Need to implement TopSecret ENABLE" >&2
+	echo "003_cert Need to implement TopSecret CONFIG" >&2
 	return 8
 }
 SetupACF2() {
-	echo "003_cert Need to implement ACF2 ENABLE" >&2
+	echo "003_cert Need to implement ACF2 CONFIG" >&2
 	return 8
 }
 
@@ -48,26 +50,26 @@ EOF
 else
 cat <<'EOF' >>${script}
 SetupRACF() {
-	export name="${ZWE1B0_PKCS11_TOKEN_NAME}"  
-	export label="${ZWE1B0_PKCS11_TOKEN_LABEL}"  
-	export user="${ZWE1B0_PKCS11_TOKEN_CREATOR}"  
+	export name="${ZWE_PKCS11_TOKEN_NAME}"  
+	export label="${ZWE_PKCS11_TOKEN_LABEL}"  
+	export user="${ZWE_PKCS11_TOKEN_CREATOR}"  
 	if `undefinedProperty "${name}"` ; then
-		echo "003_cert ZWE1B0_PKCS11_TOKEN_NAME must be defined" >&2
+		echo "003_cert ZWE_PKCS11_TOKEN_NAME must be defined" >&2
 		return 8
 	fi
 	if `undefinedProperty "${label}"` ; then
-		echo "003_cert ZWE1B0_PKCS11_TOKEN_LABEL must be defined" >&2
+		echo "003_cert ZWE_PKCS11_TOKEN_LABEL must be defined" >&2
 		return 8
 	fi
 	if `undefinedProperty "${user}"` ; then
-		echo "003_cert ZWE1B0_PKCS11_TOKEN_CREATOR must be defined" >&2
+		echo "003_cert ZWE_PKCS11_TOKEN_CREATOR must be defined" >&2
 		return 8
 	fi
 
 	racfSetGenericClasses "CRYPTOZ"
-	chk "$?" "Unable to configure ZWE1B0"
+	chk "$?" "Unable to configure ${sw}"
 	racfActivateAndShareClasses "CRYPTOZ"
-	chk "$?" "Unable to configure ZWE1B0"
+	chk "$?" "Unable to configure ${sw}"
 
 	if ! `racfProfileExists "CRYPTOZ" "SO.**"` ; then
 		issueTSO "RDEFINE CRYPTOZ SO.** UACC(NONE)"
@@ -78,44 +80,44 @@ SetupRACF() {
 		chk "$?" "Unable to define CRYPTOZ profile USER.${PKCS11_TOKEN_NAME}"
 	fi
 	racfPermitUsers "CRYPTOZ" "SO.**" "UPDATE" "${user}"
-	chk "$?" "Unable to configure ZWE1B0"
+	chk "$?" "Unable to configure ${sw}"
 
 	racfPermitUsers "CRYPTOZ" "USER.${name}" "UPDATE" "${user}"
-	chk "$?" "Unable to configure ZWE1B0"
+	chk "$?" "Unable to configure ${sw}"
 
 	racfRefreshClasses "CRYPTOZ"
-	chk "$?" "Unable to configure ZWE1B0"
+	chk "$?" "Unable to configure ${sw}"
 
 	return 0
 }
 
 SetupTopSecret() {
-	echo "003_cert Need to implement TopSecret DISABLE" >&2
+	echo "003_cert Need to implement TopSecret DECONFIG" >&2
 	return 8
 }
 
 SetupACF2() {
-	echo "003_cert Need to implement ACF2 DISABLE" >&2
+	echo "003_cert Need to implement ACF2 DECONFIG" >&2
 	return 8
 }
 SetupCertificates() {
 	ZOWE_ROOT="${ZOSPM_TGT_ZFSROOT}/usr/lpp/zowe/"
 	zospmZoweConfigFile="${ZOSPM_TMP}/zoweconfig.$$.tmp"
 	echo "
-              	HOSTNAME=${ZWE1B0_HOSTNAME}
-		IPADDRESS=${ZWE1B0_IPADDRESS}
-		VERIFY_CERTIFICATES=${ZWE1B0_VERIFY_CERTIFICATES}
-		EXTERNAL_CERTIFICATE=${ZWE1B0_EXTERNAL_CERTIFICATE}
-		EXTERNAL_CERTIFICATE_ALIAS=${ZWE1B0_CERTIFICATE_ALIAS}
+              	HOSTNAME=${ZWE_HOSTNAME}
+		IPADDRESS=${ZWE_IPADDRESS}
+		VERIFY_CERTIFICATES=${ZWE_VERIFY_CERTIFICATES}
+		EXTERNAL_CERTIFICATE=${ZWE_EXTERNAL_CERTIFICATE}
+		EXTERNAL_CERTIFICATE_ALIAS=${ZWE_CERTIFICATE_ALIAS}
 		EXTERNAL_CERTIFICATE_AUTHORITIES=${ZOSPM_CERTIFICATE_AUTHORITES}
 		ZOSMF_CERTIFICATE=${ZOS240_ZOSMF_CERTIFICATE}
-		KEYSTORE_PASSWORD=${ZWE1B0_KEYSTORE_PASSWORD}
-		KEYSTORE_DIRECTORY=${ZWE1B0_KEYSTORE_DIRECTORY}
-		KEYSTORE_ALIAS=${ZWE1B0_KEYSTORE_ALIAS}
-		ZOWE_USER_ID=${ZWE1B0_ZOWEUSER}
-		ZOWE_GROUP_ID=${ZWE1B0_ADMINGRP}
-		PKCS11_TOKEN_NAME=${ZWE1B0_PKCS11_TOKEN_NAME}  
-		PKCS11_TOKEN_LABEL=${ZWE1B0_PKCS11_TOKEN_LABEL}  
+		KEYSTORE_PASSWORD=${ZWE_KEYSTORE_PASSWORD}
+		KEYSTORE_DIRECTORY=${ZWE_KEYSTORE_DIRECTORY}
+		KEYSTORE_ALIAS=${ZWE_KEYSTORE_ALIAS}
+		ZOWE_USER_ID=${ZWE_ZOWEUSER}
+		ZOWE_GROUP_ID=${ZWE_ADMINGRP}
+		PKCS11_TOKEN_NAME=${ZWE_PKCS11_TOKEN_NAME}  
+		PKCS11_TOKEN_LABEL=${ZWE_PKCS11_TOKEN_LABEL}  
 	" >${zospmZoweConfigFile}
 	${ZOWE_ROOT}/bin/zowe-setup-certificates.sh -p ${zospmZoweConfigFile}
 
@@ -125,7 +127,8 @@ EOF
 fi
 
 cat <<'EOF' >>${script}
-. zospmsetswenv zwe1b0
+export sw="${sw}"
+. zospmsetswenv "${sw}"
 #set -x
 sp=`secmgr`
 if [ "${sp}" = "RCVT" ]; then                                       
diff --git a/generate/004_zicg b/generate/004_zicg
--- a/generate/004_zicg
+++ b/generate/004_zicg
@@ -1,11 +1,12 @@
 #!/bin/sh
 
-if ! [ $# -eq 2 ]; then
-	echo "Syntax: 004_zicfg ENABLE|DISABLE <output-script>" >&2
+if ! [ $# -eq 3 ]; then
+	echo "Syntax: 004_zicfg <sw> CONFIG|DECONFIG <output-script>" >&2
 	exit 8
 fi
-verb="$1"
-script="$2"
+sw="$1"
+verb="$2"
+script="$3"
 
 zospm=`whence zospm`
 zospmdir=${zospm%/*}
@@ -16,46 +17,47 @@ cat << EOF >${script}
 #set -x
 export verb="${verb}"
 export PATH=${zospmdir}:\$PATH
-. zospmsetswenv zwe1b0
+export sw="${sw}"
+. zospmsetswenv "${sw}"
 
 set +x
 zowedir="\${ZOSPM_TGT_ZFSROOT}usr/lpp/zowe"
-zoweinstancedir="\${ZWE1B0_INSTANCE_ROOT}"
+zoweinstancedir="\${ZWE_INSTANCE_ROOT}"
 EOF
 
 if [ $? -gt 0 ]; then
-	echo "Unable to create ZWE1B0 Update script: ${script}." >&2
+	echo "Unable to create ${sw} Update script: ${script}." >&2
 	exit 16
 fi
 chmod u+x "${script}"
 
-if [ "${verb}" = "ENABLE" ]; then
+if [ "${verb}" = "CONFIG" ]; then
 cat <<'EOF' >>${script}
-	chkProperties "ZOSPM_JAVA_HOME ZOSPM_NODE_HOME ZWE1B0_IPADDRESS" 
+	chkProperties "ZOSPM_JAVA_HOME ZOSPM_NODE_HOME ZWE_IPADDRESS" 
 	if [ $? -gt 0 ]; then
 		echo "004_zicfg failed." >&2
 		exit 8
 	fi
 	export JAVA_HOME="${ZOSPM_JAVA_HOME}"
 	export NODE_HOME="${ZOSPM_NODE_HOME}"
-	export ZOWE_EXPLORER_HOST="${ZWE1B0_IPADDRESS}"
-	export ZOWE_IP_ADDRESS="${ZWE1B0_IPADDRESS}"
-	export ZOWE_ZOSMF_HOST="${ZWE1B0_IPADDRESS}"
+	export ZOWE_EXPLORER_HOST="${ZWE_IPADDRESS}"
+	export ZOWE_IP_ADDRESS="${ZWE_IPADDRESS}"
+	export ZOWE_ZOSMF_HOST="${ZWE_IPADDRESS}"
 
 	"${zowedir}/bin/zowe-configure-instance.sh" -c "${zoweinstancedir}"
 
 	cat <<NESTEOF >>"${zoweinstancedir}/instance.env"
 
-		CATALOG_PORT="${ZWE1B0_CATALOG_PORT}"
-		DISCOVERY_PORT="${ZWE1B0_DISCOVERY_PORT}"
-		GATEWAY_PORT="${ZWE1B0_GATEWAY_PORT}"
-		JOBS_API_PORT="${ZWE1B0_JOBS_API_PORT}"
-		FILES_API_PORT="${ZWE1B0_FILES_API_PORT}"
-		JES_EXPLORER_UI_PORT="${ZWE1B0_JES_EXPLORER_UI_PORT}"
-		MVS_EXPLORER_UI_PORT="${ZWE1B0_MVS_EXPLORER_UI_PORT}"
-		USS_EXPLORER_UI_PORT="${ZWE1B0_USS_EXPLORER_UI_PORT}"
-		ZOWE_ZLUX_SERVER_HTTPS_PORT="${ZWE1B0_ZOWE_ZLUX_SERVER_HTTPS_PORT}"
-		ZOWE_ZSS_SERVER_PORT="${ZWE1B0_ZOWE_ZSS_SERVER_PORT}"
+		CATALOG_PORT="${ZWE_CATALOG_PORT}"
+		DISCOVERY_PORT="${ZWE_DISCOVERY_PORT}"
+		GATEWAY_PORT="${ZWE_GATEWAY_PORT}"
+		JOBS_API_PORT="${ZWE_JOBS_API_PORT}"
+		FILES_API_PORT="${ZWE_FILES_API_PORT}"
+		JES_EXPLORER_UI_PORT="${ZWE_JES_EXPLORER_UI_PORT}"
+		MVS_EXPLORER_UI_PORT="${ZWE_MVS_EXPLORER_UI_PORT}"
+		USS_EXPLORER_UI_PORT="${ZWE_USS_EXPLORER_UI_PORT}"
+		ZOWE_ZLUX_SERVER_HTTPS_PORT="${ZWE_ZOWE_ZLUX_SERVER_HTTPS_PORT}"
+		ZOWE_ZSS_SERVER_PORT="${ZWE_ZOWE_ZSS_SERVER_PORT}"
 NESTEOF
 	a2e "${zoweinstancedir}/instance.env"
 EOF
diff --git a/generate/005_xmcfg b/generate/005_xmcfg
--- a/generate/005_xmcfg
+++ b/generate/005_xmcfg
@@ -1,11 +1,12 @@
 #!/bin/sh
 
-if ! [ $# -eq 2 ]; then
-	echo "Syntax: 003_xmemcfg ENABLE|DISABLE <output-script>" >&2
+if ! [ $# -eq 3 ]; then
+	echo "Syntax: 003_xmemcfg <sw> CONFIG|DECONFIG <output-script>" >&2
 	exit 8
 fi
-verb="$1"
-script="$2"
+sw="$1"
+verb="$2"
+script="$3"
 
 zospm=`whence zospm`
 zospmdir=${zospm%/*}
@@ -16,31 +17,32 @@ cat << EOF >${script}
 #set -x
 export verb="${verb}"
 export PATH=${zospmdir}:\$PATH
-. zospmsetswenv zwe1b0
+export sw="${sw}"
+. zospmsetswenv "${sw}"
 
 set +x
-authlib="\${ZOSPM_TGT_HLQ}ZWE1B0.SZWEAUTH"
-srclib="\${ZOSPM_TGT_HLQ}ZWE1B0.SZWESAMP"
+authlib="\${ZOSPM_TGT_HLQ}${sw}.SZWEAUTH"
+srclib="\${ZOSPM_TGT_HLQ}${sw}.SZWESAMP"
 parmlib="\${ZOSPM_TGT_HLQ}PARMLIB"
 proclib="\${ZOSPM_TGT_HLQ}PROCLIB"
 EOF
 
 if [ $? -gt 0 ]; then
-	echo "Unable to create ZWE1B0 Update script: ${script}." >&2
+	echo "Unable to create ${sw} Update script: ${script}." >&2
 	exit 16
 fi
 chmod u+x "${script}"
 
-if [ "${verb}" = "ENABLE" ]; then
+if [ "${verb}" = "CONFIG" ]; then
 cat <<'EOF' >>${script}
 	swesip=`cat "//'${srclib}(ZWESIP00)'"`
 
 	sijcl=`cat "//'${srclib}(ZWESISTC)'"`
-	sijcl=`jclReplaceDD "${sijcl}" "ZWESIS01" "STEPLIB" "${ZOSPM_TGT_HLQ}ZWE1B0.SZWEAUTH"`
+	sijcl=`jclReplaceDD "${sijcl}" "ZWESIS01" "STEPLIB" "${ZOSPM_TGT_HLQ}${sw}.SZWEAUTH"`
 	sijcl=`jclReplaceDD "${sijcl}" "ZWESIS01" "PARMLIB" "${parmlib}"`
 
 	sajcl=`cat "//'${srclib}(ZWESASTC)'"`
-	sajcl=`jclReplaceDD "${sajcl}" "ZWESAUX" "STEPLIB" "${ZOSPM_TGT_HLQ}ZWE1B0.SZWEAUTH"`
+	sajcl=`jclReplaceDD "${sajcl}" "ZWESAUX" "STEPLIB" "${ZOSPM_TGT_HLQ}${sw}.SZWEAUTH"`
 EOF
 else
 cat <<'EOF' >>${script}
@@ -51,24 +53,24 @@ EOF
 fi
 
 cat <<'EOF' >>${script}
-procregistrar zwe1b0 "${verb}" ZWESISTC "${sijcl}"
+procregistrar "${sw}" "${verb}" ZWESISTC "${sijcl}"
 chk "$?" "Unable to ${verb} proclib member ${proclib}(ZWESISTC)"
 
-procregistrar zwe1b0 "${verb}" ZWESASTC "${sajcl}"
+procregistrar "${sw}" "${verb}" ZWESASTC "${sajcl}"
 chk "$?" "Unable to ${verb} proclib member ${proclib}(ZWESASTC)"
 
-profhdr="//* ZWE1B0 start */"
-profftr="//* ZWE1B0 end */"
+profhdr="//* ${sw} start */"
+profftr="//* ${sw} end */"
 
-registrar "ZWE1B0" "${verb}" "${parmlib}" "ZWESIP00" "$profhdr" "$profftr" "//*" "*/" "${zwesip}"
+registrar "${sw}" "${verb}" "${parmlib}" "ZWESIP00" "$profhdr" "$profftr" "//*" "*/" "${zwesip}"
 chk "$?" "Unable to ${verb} ${parmlib}(ZWESIP00)"
 
-apfregistrar zwe1b0 "${verb}" "${authlib}"
+apfregistrar "${sw}" "${verb}" "${authlib}"
 chk "$?" "Unable to ${verb} APF Authorization of ${authlib}"
  
 pptText="PPT PGMNAME(ZWESIS01) KEY(4) NOSWAP
 PPT PGMNAME(ZWESAUX) KEY(4) NOSWAP"
-pptregistrar zwe1b0 "${verb}" "${pptText}"
+pptregistrar "${sw}" "${verb}" "${pptText}"
 chk "$?" "Unable to ${verb} PPT entries"
 
 exit $?
diff --git a/generate/006_svcfg b/generate/006_svcfg
--- a/generate/006_svcfg
+++ b/generate/006_svcfg
@@ -1,11 +1,12 @@
 #!/bin/sh
 
-if ! [ $# -eq 2 ]; then
-	echo "Syntax: 006svcfg ENABLE|DISABLE <output-script>" >&2
+if ! [ $# -eq 3 ]; then
+	echo "Syntax: 006svcfg <sw> CONFIG|DECONFIG <output-script>" >&2
 	exit 8
 fi
-verb="$1"
-script="$2"
+sw="$1"
+verb="$2"
+script="$3"
 
 zospm=`whence zospm`
 zospmdir=${zospm%/*}
@@ -16,20 +17,21 @@ cat << EOF >${script}
 #set -x
 export verb="${verb}"
 export PATH=${zospmdir}:\$PATH
-. zospmsetswenv zwe1b0
+export sw="${sw}"
+. zospmsetswenv "${sw}"
 
 set +x
 proclib="\${ZOSPM_TGT_HLQ}PROCLIB"
-zoweinstancedir="\${ZWE1B0_INSTANCE_ROOT}"
+zoweinstancedir="\${ZWE_INSTANCE_ROOT}"
 EOF
 
 if [ $? -gt 0 ]; then
-	echo "Unable to create ZWE1B0 Update script: ${script}." >&2
+	echo "Unable to create ${sw} Update script: ${script}." >&2
 	exit 16
 fi
 chmod u+x "${script}"
 
-if [ "${verb}" = "ENABLE" ]; then
+if [ "${verb}" = "CONFIG" ]; then
 cat <<'EOF' >>${script}
 	decho "//* ZWESVSTC: Started task to run Zowe
 //ZWESVSTC   PROC INSTANCE='${zoweinstancedir}'
